
name = "notice"
main = "./src/worker.ts"
compatibility_date = "2024-01-01"

[vars]
TELEGRAM_TOKEN = ""

[[d1_databases]]
binding = "DB"
database_name = "expiry-db"
database_id = ""

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "expiry-reminder-assets"

[site]
bucket = "./frontend"

[triggers]
crons = ["0 0 * * *"] # 每天 00:00 America/Los_Angeles


