
name = "notice"
main = "./src/worker.ts"
compatibility_date = "2024-01-01"

[vars]
TELEGRAM_TOKEN = ""

[[d1_databases]]
binding = "DB"
database_name = "expiry-db"
database_id = "004820c6-4571-4b7b-89b6-8789a20619ac"



[site]
bucket = "./frontend"

[triggers]
crons = ["0 0 * * *"] # 每天 00:00 America/Los_Angeles


