name = "notice"
main = "./src/worker.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "notice"
database_id = "004820c6-4571-4b7b-89b6-8789a20619ac"

[assets]
directory = "./frontend"
binding   = "ASSETS"
run_worker_first = ["/api/*"]
not_found_handling = "single-page-application"

[triggers]
crons = ["*/5 * * * *"]   # 每 5 分钟执行 scheduled()
